name: rombmarketingstrategy
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.13
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  firebase_core: ^1.15.0
  firebase_storage: ^10.2.14
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_screenutil: ^5.4.0+1
  flutter_svg: ^1.0.3
  internet_connection_checker: ^0.0.1+3
  lottie: ^1.3.0
  signature: ^5.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/favicon.png"
  adaptive_icon_background: "#ffffff"
