name: rombmarketingstrategy
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  # flutter pub run easy_localization:generate --source-dir ./assets/translations
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.4.0+1
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/logo.svg
  fonts:
    - family: Monsterrat
      fonts:
        - asset: assets/fonts/Monsterrat.ttf
